# models/call_models.py
from pydantic import BaseModel
from typing import Optional


class IncomingCallData(BaseModel):
    """Data received from Twilio's incoming call webhook."""
    From: str = "Unknown"
    To: str = ""
    CallSid: str = ""
    CallStatus: str = ""
    Direction: str = ""


class CallEndedData(BaseModel):
    """Data received from Twilio when a call ends."""
    CallSid: str = ""
    From: str = ""
    To: str = ""
    CallDuration: str = "0"
    CallStatus: str = ""


class CallbackRequest(BaseModel):
    """Request from Flutter app to trigger an AI callback."""
    to_number: str
    your_message: str
    caller_name: str
    call_log_id: str


class TranscriptEntry(BaseModel):
    """A single entry in a call transcript."""
    speaker: str  # 'caller' | 'assistant'
    text: str


class CallSummary(BaseModel):
    """Structured summary generated by Claude after a call."""
    caller_name: str = "Unknown"
    caller_relationship: str = "unknown"
    purpose: str = ""
    summary: str = ""
    key_details: list[str] = []
    urgency: str = "low"
    call_type: str = "routine"
    action_needed: str = ""
    recommended_response: str = ""
    deadline: str = ""
    should_call_back: bool = False


class FCMTokenRequest(BaseModel):
    """Request to register a new FCM token."""
    fcm_token: str
    device_id: Optional[str] = None
